### ISSUE TITLE
抓取数据键值

### ISSUE THREAD

**Issue by bbtfr** [cinabre/todo#1]
初步计划，抓取数据包括以下内容：

id：数据库唯一ID，例如用MongoDB的话就是ObjectID；
title：产品标题；
description：产品描述；（这块可能内容比较多，所以在考虑需不需要存下来）；
url：产品原网址链接；
covers：产品图片，一个包含多个图片链接的数组；
store：店铺（amazon, jingdong etc.）

**Comment by bbtfr** [comment]
恩，最好再有个category，保存产品分类信息，不过直接存成一个字符串还是怎么处理没想好

**Comment by luoshuifish** [comment]
商品名称：     芙优润芦荟仙人掌深层补水面膜 25ml x 10片  
品        牌：   芙优润(Premium Care)
分        类：   面膜
功        效：   紧致,均匀肤色,持久,祛痘,保湿,修护肌肤,美白,补水,滋润,修护,抗衰老,舒缓,净肤,祛斑,嫩肤,抗氧化,排毒,净化,柔肤,消肿,修饰,淡化黑色素,改善肤质,缩小毛孔,护理
产地：   广州
包装：   有盒有塑封
规格：   25ml/片x 10片
保质期：    3年（以收到具体实物为准）
适用人群：     所有肌肤，尤其适合干燥缺水、肤色暗黄，需要补水保湿的MM~
特别说明：     如有不适，请停止使用。

抓取的信息中没有产品的价格？
description：产品描述；这里对应的是上面功效中的内容，关键词对搜索有用，确实我们前期可能不用保存这些信息
，只需把初步的原型搭起来

category：产品分类信息，可能是可变的字符串数组，即一种产品对应1-几个分类信息

我基本调研了solr， sensei分布式开源搜索框架，后期可以采用sensei建我们的分布式搜索引擎，但前期的话，我们只在单机上做，过程基本上是爬虫得到的数据放mongodb中，我用lucene给mongodb中的数据建索引什么的，关键词的话，将商品名称进行分词得到（分词也有现在的库），搜索的话以名字，或名字中的关键词搜索。所以下一步，我的主要工作是完成如何用lucene建索引什么的，在单机上搭起具有基本搜索功能的搜索引擎。

**Comment by bbtfr** [comment]
我自己没用过slor做项目，不过听说lucene保存全文索引的时候也会把原来的文本存下来，可以当数据库用

**Comment by bbtfr** [comment]
恩，忘了价格，所以字段的选择上
加一个price
covers改成thumbnail好了，就存个缩略图链接

description和covers都在具体产品介绍页面上，其他信息在产品目录或者产品搜索结果页上就能抓到，为了多几条信息，需要遍历的页面多很多，有点不划算

那字段暂定为
- id：数据库唯一ID，例如用MongoDB的话就是ObjectID；
- title：产品标题；
- price：产品价格；
- category：产品分组；（这个也先看看再说，有可能咱自己来定分组，而不是直接爬取电商网站上的）
- url：产品原网址链接；
- thumbnail：产品缩略图链接；
- store：店铺（amazon, jingdong etc.）
