### ISSUE TITLE
都有啥进展？

### ISSUE THREAD

**Issue by bbtfr** [cinabre/todo#3]
RT

**Comment by luoshuifish** [comment]
1、Lucene的基本原理基本摸清，我正在做一个小的demo，去演示一下整个检索过程
2、上次关于Lucene做数据库的问题，Lucene不具备做数据库的能力，所以我们还是要选一种数据库去存取我们爬的数据，后面就是数据库与Lucene整合的过程了，这方面肯定要做些工作

**Comment by luoshuifish** [comment]
定好数据库的话，我还要写一个数据库访问的接口，从其中取要索引的数据，当然索引肯定需要定时重建，例如一天一次什么，到时可能只能根据数据库的时间戳去搞了

**Comment by bbtfr** [comment]
索引能用增量索引么？动态的添加新索引
在 2013-5-22 下午6:36，"yuyongjiang" notifications@github.com写道：

**Comment by luoshuifish** [comment]
最近英语课结课，搬家什么的，没来及看邮箱，增量索引，lucene有一个参数去设，不过可能不太好使，其实最主要的原因，如果是数据库的数据只增的话，索引增加，应该好做，但是最怕的是，以前存储一部分数据要删除，这个用增量索引确实困难了，我要查查资料看下有没有好的解决方法，网上说似乎有一个叫什么的框架能把事务和索引对应起来，但是要是有简单的解决方法的话更好

**Comment by bbtfr** [comment]
所以才想着最好能把数据存到lucene里

以前用sphinx这么干过,在sphinx里,数据分为field和attribute,field会做分词和全文索引,attribute只是用来过滤结果和排序,所以就把原文存在field和attribute里各一份,field里的分词做全文索引,attribute这份只负责提原始数据,这样把所有内容存到一个地方,增量索引和删除索引都简单多了

不知道lucene能不能这么做
